### ISSUE TITLE
Add grid type

### ISSUE THREAD

**Issue by neerdoc** [j9brown/decluttering-card#3]
**Is your feature request related to a problem? Please describe.**
I have 20+ sensors that are all the same. I like the new _sections_ grid layout, and it would be awesome if I could create a reusable grid.

**Describe the solution you'd like**
That I can create one grid template and reuse it with only a few variables to setup.

**Describe alternatives you've considered**
Well, that would be a very long yaml file which I have to edit a lot if I want to change the look of each sensor.

**Additional context**
As an example, something like this yaml should work:
```
views:
  - type: sections
    max_columns: 4
    title: Basement
    path: basement
    sections:
      - type: custom:decluttering-template
        template: power_switch_meter
        grid:
          cards:
            - type: heading
              heading: '[[heading]]'
              heading_style: title
              icon: '[[icon]]'
            - type: tile
              entity: switch.'[[sensor_name]]'
              name: On/Off
              vertical: true
            - type: tile
              entity: switch.'[[sensor_name]]''[[second_switch]]'
              name: On/Off (Right)
              vertical: true
            - graph: line
              type: sensor
              entity: sensor.'[[sensor_name]]'_energy_power
              detail: 1
              grid_options:
                columns: full
            - type: tile
              entity: sensor.'[[sensor_name]]'_energy_today
              name: Energy Today
            - type: tile
              entity: sensor.'[[sensor_name]]'_energy_total
              name: Energy Total
              vertical: true
              show_entity_picture: false
              grid_options:
                columns: 12
                rows: 2
      - type: custom:decluttering-card
        template: power_switch_meter
        variables:
          - heading: Pool Pump
          - icon: mdi:pool
          - sensor_name: poolpump
          - second_switch: _tasmota_2
      - type: custom:decluttering-card
        template: power_switch_meter
        variables:
          - heading: Freezer
          - icon: mdi:snowflake
          - sensor_name: freezer
          - second_switch: _tasmota_2

```
