### ISSUE TITLE
grid_rows still not working

### ISSUE THREAD

**Issue by LordShadowen** [j9brown/decluttering-card#5]
First off, thanks for this fork - like others, I love the declutering-card and being able to use it with the new sections dashboard is absolutely awesome.

This is the same issue as reported in #1, but that issue was closed, so I created a new one (apologies if there was a better way do it).

I have found this issue, specifically when using the very popular Mushroom cards. 
For example, the Mushroom Template card (which I use a lot) does not fill the height specified by the rows, but I think this applies to all of them.

I did a little digging in the DOM, and it seems that when a Mushroom card is used directly, it has an attribute `layout="grid"` which gives it a height of 100%.
When the same card is used inside a decluttering-card, it lacks this attribute.

I don't know how that works - if it's something in the Mushroom code that detects that it's being used in a sections/grid or something that HA does to "compatible" cards automatically.
For example, the native Tile card does not have this attribute but it works fine....

**Comment by j9brown** [comment]
Could you provide a YAML snippet that exhibits the issue?

**Comment by LordShadowen** [comment]
While creating a test case to demonstrate this, I got a better understanding of what's going on....
I don't think it's necessarily a bug anymore, but more of an inconsistency between the UI and the generated YAML code of Home Assistant itself. 

It basically depends on the value of `rows` under `grid_options`.

For example, create a template like this:

```
  test:    
    card:
      type: custom:mushroom-template-card
      primary: Line1
      secondary: Line2
      icon: mdi:mushroom
      vertical: true
```

Note the "vertical" attribute.

Next, on a View using Sections layout, create this section:

```
type: grid
cards:
  - type: custom:mushroom-template-card
    primary: Line1
    secondary: Line2
    icon: mdi:mushroom
    vertical: true
    grid_options:
      columns: 3
  - type: custom:decluttering-card
    template: test
    grid_options:
      columns: 3
```

You'll see that the heights don't align:

<img width="464" height="215" alt="Image" src="https://github.com/user-attachments/assets/2eb0bc3b-01ec-4b82-8698-0a6388932ab1" />

This is because we didn't specify any value of `rows`, and this is what happens if we don't touch the rows slider on the UI. If we touch it, it will always add a `rows: 1` or a `rows: 2` or whatever number. If `rows: 2` is present, then it aligns. 

```
type: grid
cards:
  - type: custom:mushroom-template-card
    primary: Line1
    secondary: Line2
    icon: mdi:mushroom
    vertical: true
    grid_options:
      columns: 3
  - type: custom:decluttering-card
    template: test
    grid_options:
      columns: 3
      rows: 2
```

<img width="474" height="197" alt="Image" src="https://github.com/user-attachments/assets/9729fe93-02c2-4d03-aaa2-62dfb73be2c0" />

You can actually see this happening in real time to the template when dragging the slider. The inconsistency is that the UI seems to suggest that the default height is 1 row. But actually, if we don't touch it, the default is _nothing_ or `rows: auto` , 

The difference is that the Tile or Mushroom Template cards seem to automatically align to either 1 or 2 rows (I'm guessing this is a requirement to be compliant with the sections layout). 
When they get wrapped within a decluttering-card, they don't - they get their "natural" height.


Now that I understand all of this, I'm not sure that I necessarily want to get this fixed :)
I actually prefer to have the option of not strictly aligning to the row heights, as I find that in some cases 1 is too little, but 2 is too much. In this example, I prefer the "natural" height of a vertical template card and I wish Home Assistant had an finer grained control to let me do this.

I wanted to share these findings anyway, but as it stands, the decluttering-card actually provides a nice workaround to get what I want....  and "fixing it" only requires specifying an actual row number.

So feel free to ignore and close this ticket :)
